# Generated by Django 4.2.7 on 2024-11-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literatureauthor',
            name='gender',
            field=models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default=0, verbose_name='性别'),
        ),
    ]
