# Generated by Django 4.2.7 on 2024-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_author', '0003_remove_literatureauthor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatureauthor',
            name='gender',
            field=models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default='0', verbose_name='性别'),
        ),
    ]
