# Generated by Django 4.2.7 on 2024-11-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature_author', '0004_literatureauthor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literatureauthor',
            name='nation',
        ),
    ]
