# Generated by Django 4.2.7 on 2024-11-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_author', '0005_remove_literatureauthor_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatureauthor',
            name='nation',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='国家'),
        ),
    ]
