# Generated by Django 4.2.7 on 2024-11-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_author', '0007_remove_literatureauthor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literatureauthor',
            name='business',
        ),
        migrations.RemoveField(
            model_name='literatureauthor',
            name='cnt_md',
        ),
        migrations.RemoveField(
            model_name='literatureauthor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='literatureauthor',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='literatureauthor',
            name='tel',
        ),
        migrations.AddField(
            model_name='literatureauthor',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部门'),
        ),
    ]
