# Generated by Django 4.2.7 on 2024-11-28 06:05

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('literature_author', '0008_remove_literatureauthor_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatureauthor',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='职务'),
        ),
        migrations.AddField(
            model_name='literatureauthor',
            name='cnt_md',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='literatureauthor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='literatureauthor',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='literatureauthor',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='电话'),
        ),
    ]
