# Generated by Django 4.2.7 on 2024-11-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature_author', '0009_literatureauthor_business_literatureauthor_cnt_md_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literatureauthor',
            name='department',
        ),
    ]
