# Generated by Django 4.2.7 on 2024-11-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature_author', '0010_remove_literatureauthor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='literatureauthor',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部门'),
        ),
    ]
