# Generated by Django 4.2.7 on 2024-11-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_country', '0001_initial'),
        ('literature_author', '0011_literatureauthor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literatureauthor',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_author', to='public_country.publiccountry', verbose_name='国家'),
        ),
    ]
