@startuml
'https://plantuml.com/sequence-diagram
!pragma teoz true


title 审核流程：创建流程,状态,状态转换及相关动作
left to right direction


管理者 --> (创建流程)
创建流程 --> (创建状态State)
创建状态State --> (创建动作Action)

rectangle 创建状态转换Transition{
    (创建状态State) --> (正常):<<没有特殊名称的常规状态>>
    (创建状态State) --> (开始):<<每个进程只应该一个。此状态是创建新请求时所处的状态>>
    (创建状态State) --> (完成):<<表示此状态下的任何请求已正常完成的状态>>
    (创建状态State) --> (取消):<<表示此状态下的任何请求已被取消的状态(例如，工作已开始但尚未完成)>>
    (创建状态State) --> (拒绝):<<表示此状态下的任何请求已被拒绝的状态(例如，从未开始且不会被处理)>>
}

rectangle 创建动作Action{
    (创建动作Action) --> (提交审核):<<操作人将将请求移回到进程中的“开始”状态>>
    (创建动作Action) --> (取消审核):<<操作人将请求应在此过程中移至“取消”状态>>
    (创建动作Action) --> (通过审核):<<操作人将请求应移至下一个状态>>
    (创建动作Action) --> (拒绝审核):<<操作人将请求应移至上一个状态>>
}
rectangle 创建转换动作TransitionAction{
    (正常) --> (开始):<<提交审核>>
    (开始) --> (取消):<<取消审核>>
    (开始) --> (拒绝):<<拒绝审核>>
    (开始) --> (完成):<<通过审核>>
    (取消) --> (拒绝):<<拒绝审核>>
    (取消) --> (完成):<<通过审核>>
    (拒绝) --> (开始):<<提交审核>>
}



@enduml
