FROM ubuntu:22.04

MAINTAINER bukun <bukun@osgeo.cn>

ENV DEBIAN_FRONTEND noninteractive

# RUN echo     "en_US.UTF-8 UTF-8" > /etc/locale.gen
# RUN echo     "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen
# RUN locale-gen
# ENV LANG en_US.UTF-8
# ENV LANGUAGE en_US:en
# ENV LC_ALL en_US.UTF-8


#########################################
RUN mkdir ~/.pip
RUN echo "[global]" > ~/.pip/pip.conf
RUN echo "index-url = http://mirrors.aliyun.com/pypi/simple" >> ~/.pip/pip.conf
RUN echo "[install]" >> ~/.pip/pip.conf
RUN echo "trusted-host=mirrors.aliyun.com" >> ~/.pip/pip.conf
##############################################################################
RUN  apt update &&  apt -y dist-upgrade 
RUN  apt install -y git python3-pip redis-server python3-venv postgresql-server-dev-all libpq-dev postgresql postgresql-contrib redis-server sudo

RUN python3 -m venv /vpy
RUN mkdir -p /coding/TorCMS
WORKDIR /coding/TorCMS
COPY xx_*.txt /coding/TorCMS/
RUN /vpy/bin/python3 -m  pip install wheel
RUN /vpy/bin/python3 -m  pip install -r /coding/TorCMS/xx_requirements.txt
RUN /vpy/bin/python3 -m  pip install -r /coding/TorCMS/xx_requirements-dev.txt


