// Generated by CoffeeScript 1.11.1


var AjaxUrl, Z, baseMaps, cities, deleteShape, drawnItems, latlng, lcontrol, map, onKeyDown, osm, redoBuffer,
    satellite_layer, save_data, show_saved_info, styleEditor;
show_saved_info = function () {
    $("#infor").css("color", "#ff0");
    $("#infor").text("用户数据已经成功保存！");
    return setTimeout("$('#infor').text('');", 8000);
};
save_data = function () {
    var shape;
    shape = drawnItems.toGeoJSON();
    map.doubleClickZoom.enable();
    return $.ajax({
        type: "POST",
        url: "/geojson/" + geojsonid,
        data: {
            geojson: JSON.stringify(shape)
        },
        dataType: "html",
        timeout: 2000,
        error: function () {
            return alert("请登陆后进行数据保存！或再次尝试进行保存！");
        },
        success: function (result) {
            var geo;
            geo = $.parseJSON(result);
            if (geo["status"] === 0) {
                return alert("请检查是否拥有数据权限！");
            } else {
                show_saved_info();
                if (geo["sig"] !== "") {
                    return location.href = "/geojson/" + geo["sig"];
                }
            }
        }
    });
};
$("#btn_add_maplet").click(function () {
    var hdata, nexrad2;
    hdata = $("#maplet_id").val();
    nexrad2 = L.tileLayer.wms("https://tile.osgeo.cn/service?", {
        layers: "mp" + hdata,
        format: "image/png",
        transparent: true,
        attribution: "Maplet2"
    });
    map.addLayer(nexrad2);
    return lcontrol.addOverlay(nexrad2, hdata);
});
$("#load_geojson").click(function () {
    var gdata, gson_arr, hdata;
    hdata = $("#hdata").val();
    gson_arr = new Array();
    gdata = $.parseJSON(hdata)["features"];
    $.each(gdata, function (i, item) {
        var myGeoJson;
        gson_arr[i] = item;
        if (login === 1) {
            myGeoJson = L.geoJson(item);
            return myGeoJson.addTo(drawnItems);
        }
    });
    if (login === 0) {
        L.geoJson(gson_arr).addTo(drawnItems);
    }
    $("#hdata").val("");
    $("#infor").css("color", "#ff0");
    $("#infor").text("已经加载GeoJson数据！");
    return setTimeout("$('#infor').text('');", 8000);
});
cities = new L.LayerGroup();
// drawnItems = new L.FeatureGroup();
osm = L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYnVrdW4iLCJhIjoiY2lqeWFjZmo4MXFubndka2lzcnZ1M2tzciJ9.C1dZUQkRZSIEKfg-DaFYpw", {
    maxZoom: 18,
    attribution: "Map data &copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a> contributors, " + "<a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA</a>, " + "Imagery © <a href=\"http://mapbox.com\">Mapbox</a>",
    id: "mapbox.satellite"
});
satellite_layer = L.tileLayer("https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYnVrdW4iLCJhIjoiY2lqeWFjZmo4MXFubndka2lzcnZ1M2tzciJ9.C1dZUQkRZSIEKfg-DaFYpw", {
    maxZoom: 18,
    attribution: "Map data &copy; <a href=\"http://openstreetmap.org\">OpenStreetMap</a> contributors, " + "<a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA</a>, " + "Imagery © <a href=\"http://mapbox.com\">Mapbox</a>",
    id: "mapbox.satellite"
});
osm.addTo(cities);
map = L.map("map", {
    center: [vlat, vlon],
    zoom: vzoom_current,
    maxZoom: vzoom_max,
    minZoom: vzoom_min,
    layers: [osm],
    editable: true,
    editOptions: {
        featuresLayer: drawnItems
    }
});
// map.addLayer(drawnItems);
// AjaxUrl = "/geojson/gson/" + geojsonid;
// if (geojsonid !== "") {
//     $.getJSON(AjaxUrl, function (gjson) {
//         var gson_arr;
//         gson_arr = new Array();
//         $.each(gjson, function (i, item) {
//             var myGeoJson;
//             gson_arr[i] = item;
//             if (login === 1) {
//                 myGeoJson = L.geoJson(item);
//                 return myGeoJson.addTo(drawnItems);
//             }
//         });
//         if (login === 0) {
//             return L.geoJson(gson_arr).addTo(drawnItems);
//         }
//     });
// }


//Leaflet.draw
var drawnItems = L.featureGroup().addTo(map);
var drawControl = new L.Control.Draw({
    draw: {
        circle: false,
        rectangle: false,
        polyline: false,
        polygon: false
    },
    edit: {featureGroup: drawnItems}
}).addTo(map);

function saveIdIW() {
    var sName = $('#shapeName').val();
    var sDesc = $('#shapeDesc').val();
    var drawings = drawnItems.getLayers(); //drawnItems is a container for the drawn objects
    drawings[drawings.length - 1].title = sName;
    drawings[drawings.length - 1].content = sDesc;
    map.closePopup();
};

map.on('draw:created', function (e) {
    var type = e.layerType;
    var layer = e.layer;
    var idIW = L.popup();
    var content = '<span><b>Shape Name</b></span><br/><input id="shapeName" type="text"/><br/><br/><span><b>Shape Description<b/></span><br/><textarea id="shapeDesc" cols="25" rows="5"></textarea><br/><br/><input type="button" id="okBtn" value="Save" onclick="saveIdIW()"/>';
    idIW.setContent(content);
    idIW.setLatLng(layer.getLatLng());
    idIW.openOn(map);
    drawnItems.addLayer(layer)
});


//Export
document.getElementById('export').onclick = function (e) {
    // Extract GeoJson from featureGroup
    var data = drawnItems.toGeoJSON();
    // Stringify the GeoJson
    var convertedData = 'text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(data));
    // Create export
    document.getElementById('export').setAttribute('href', 'data:' + convertedData);
    document.getElementById('export').setAttribute('download', 'drawnItems.geojson');
    baseMaps = {
        "MapBox底图": osm,
        "卫星影像": satellite_layer
    };
    return lcontrol = L.control.layers(baseMaps, null).addTo(map);
};

//# sourceMappingURL=fullscreendraw.js.map
