"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from cfg import DB_INFO, CACHES_INFO, DEBUG_CFG

from django.views.generic import TemplateView
from django.utils.translation import gettext_lazy as _
from .conf_simpleui import *
from .conf_ckeditor import *
from .conf_leaflet import *
from .conf_mdeditor import *
from .conf_install_apps import *

# from django.utils.translation import ugettext_lazy as _


WAGTAIL_SITE_NAME = 'WAGTAIL ADMIN'
SITE_ID = int(os.environ.get('SITE_ID', 1))

# from django.conf import settings
# DEFAULT_LEVEL_INDICATOR = getattr(settings, "MPTT_DEFAULT_LEVEL_INDICATOR", "---")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).parent.parent.resolve()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2@0v#aiu_edfdl2z286icz7r)_u&bua%f3f@b2$+#_yw$-a1p5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DEBUG_CFG
AUTH_USER_MODEL = 'users.MyUser'
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # access有效时间
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # refresh有效时间
    'ROTATE_REFRESH_TOKENS': True,
}
LOGOUT_REDIRECT_URL = "/admin/"
# Application definition

# 访问django后台，提示CSRF验证失败. 请求被中断.
# https://blog.csdn.net/weixin_37770279/article/details/124480045
CSRF_TRUSTED_ORIGINS = ['https://cms.igadc.cn']



DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
# 设置文件上传处理器
FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]
MPTT_COMMENTS_ALLOW_ANONYMOUS = True  # True 为允许匿名评论，否则不允许

# CACHES = CACHES_INFO
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 引擎（默认）
# SESSION_COOKIE_NAME = "sessionid"  # Session的cookie保存在浏览器上时的key，
# SESSION_COOKIE_PATH = "/"  # Session的cookie保存的路径（默认）
# SESSION_COOKIE_DOMAIN = None  # Session的cookie保存的域名（默认）
# SESSION_COOKIE_SECURE = False  # 是否Https传输cookie（默认）
# SESSION_COOKIE_HTTPONLY = True  # 是否Session的cookie只支持http传输（默认）
# SESSION_COOKIE_AGE = 60 * 30  # Session的cookie失效日期（30min）（默认）
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 是否关闭浏览器使得Session过期（默认）
# SESSION_SAVE_EVERY_REQUEST = True  # 是否每次请求都保存Session，默认修改之后才保存

IMPORT_EXPORT_USE_TRANSACTIONS = True
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',  # 使用OAuth登录认证

    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',

    ],
    # # 全局使用限流类
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '30/min',
    #     'user': '50/min'
    # },
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # 最后别忘了加入LocaleMiddleware这个中间件。
    # 它的位置也很重要，应于SessionMiddleware之后，CommonMiddleware之前。
    'django.middleware.locale.LocaleMiddleware',  # 新增多语支持
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',  # 注意顺序
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',

]
# 即为可供资源拥有者(Django User)选择的 当第三方网站调用该网站资源时获取的权限范围。

OAUTH2_PROVIDER = {
    # OIDC 的配置。如果要用，须得在 JupyterHub 中对应配置。目前未成功。
    "OIDC_ENABLED": False,
    "PKCE_REQUIRED": False,
    "SCOPES": {
        "openid": "OpenID scope",
        "read": "Read scope",
        "write": "Write scope",
        "groups": "Access to your groups",
    },
}

OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = 'oauth2_provider.AccessToken'
OAUTH2_PROVIDER_ID_TOKEN_MODEL = 'oauth2_provider.IdToken'
OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'
OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = 'oauth2_provider.RefreshToken'

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "oauth2_provider.backends.OAuth2Backend",
)

X_FRAME_OPTIONS = 'SAMEORIGIN'
ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 设置模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },

    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

DATABASES = {
    'default': DB_INFO
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'zh-hans'
#
# TIME_ZONE = 'Asia/Shanghai'

'''
LANGUAGE_CODE = 'en-US'
# 指定支持语言。这里为了简化只支持简体中文和英文
LANGUAGES = (
    ('en', _('English')),
    ('zh', _('Simplified Chinese')),
)

# 用于存放django.po和django.mo编译过的翻译文件
PROJECT_ROOT = os.path.dirname(os.path.realpath(__name__))
LOCALE_PATHS = (
    os.path.join(PROJECT_ROOT, 'locale'),
)
'''

TIME_ZONE = 'UTC'

# USE_I18N = True

USE_TZ = True

USE_L10N = True  # 默认False，以本地化格式显示数字和时间

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),
                    os.path.join(BASE_DIR, 'yy_static_html'),
                    os.path.join(BASE_DIR, 'yy_media'), ]

# 部署环境静态文件目录
STATIC_ROOT = os.path.join(BASE_DIR, 'xx_static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'yy_media')  # 上传图片的根目录
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MIDDLEWARE_CLASSES = (
#
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.common.CommonMiddleware', # 注意顺序
#
# )
# 跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = (
#     '*'
# 'http://127.0.0.1:8080'
# )

# 异步支持,爬取数据时处理
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

ALLOWED_HOSTS = ['*']
CORS_ALLOWED_ORIGINS_REGEXES = [
    r'^https://.*?$',
]
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)
